// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by the CanvasStorageGenerator

import 'package:vide/widget_storage.dart';



/// Returns a CanvasObjectStorage containing all canvas object positions in this project
CanvasObjectStorage getAllCanvasObjectStorage() {
  return CanvasObjectStorage(
    shards: [

    ],
  );
}
