// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by Vide CLI to run the Vide canvas.

import 'package:flutter/material.dart';
import 'package:vide/vide.dart' as vide;
import 'package:vide/features/logging/zone_print_handler.dart';
import 'widget_registry.dart' as registry;
import 'canvas_storage.dart' as storage;
import 'test_registry.dart' as test_registry;
import 'lib/get_reload_counter.dart' as reload_counter;

void main() async {
  // Wrap everything in the print handler zone to catch widget logs
  ZonePrintHandler.runWithPrintHandler(() async {
    // Ensure bindings are initialized before calling Vide
    WidgetsFlutterBinding.ensureInitialized();

    // Setup Vide with the necessary data providers
    vide.Vide.setup(
      getAllPrototypeCollections: registry.getAllPrototypeCollections,
      getAllCanvasObjectStorage: storage.getAllCanvasObjectStorage,
      getAllTestCollections: test_registry.getAllTestCollections,
      getReloadId: reload_counter.reloadId,
    );

    // Run Vide canvas application
    runApp(vide.Vide());
  });
}
