// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by the TestRegistryGenerator

import 'package:vide/features/test/framework/vide_tester.dart';



/// Internal function to build the map of all tests, indexed by 'testId:description'
Map<String, VideTest> _buildAllTests() {
  return {

  };
}

/// Returns a map of all test collections in this project
/// The key is the relative path from lib with '/' preserved
Map<String, List<VideTest>> getAllTestCollections() {
  final collections = <String, List<VideTest>>{};
  final allTests = _buildAllTests(); // Call the function here
  for (final entry in allTests.entries) {
    // Assuming description does not contain the first ':' character
    final separatorIndex = entry.key.indexOf(':');
    if (separatorIndex != -1) {
      final testId = entry.key.substring(0, separatorIndex);
      final test = entry.value;
      (collections[testId] ??= []).add(test);
    }
  }
  return collections;
}

/// Returns a specific test by its ID and description
VideTest? findTest(String testId, String description) {
  final allTests = _buildAllTests(); // Call the function here
  return allTests['$testId:$description'];
}
