// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by the WidgetRegistryGenerator

import 'package:flutter/widgets.dart';
// TODO: Use a configurable path or relative path calculation if possible
import 'package:vide/widget_prototype.dart';

import 'lib/widgets/app_logo.wrapper.dart' as widgets_app_logo;
import 'lib/widgets/custom_text_field.wrapper.dart' as widgets_custom_text_field;
import 'lib/widgets/primary_button.wrapper.dart' as widgets_primary_button;


/// Returns a map of all widget prototype collections in this project
/// The key is the relative path from lib with '/' preserved
/// Each collection contains multiple variations of the same widget
Map<String, WidgetPrototypeCollection> getAllPrototypeCollections() {
  return {
  'widgets/app_logo': widgets_app_logo.getPrototypes(),
  'widgets/custom_text_field': widgets_custom_text_field.getPrototypes(),
  'widgets/primary_button': widgets_primary_button.getPrototypes(),

  };
}
